### stage 0, build time
FROM adoptopenjdk/openjdk11 as build-stage
WORKDIR /usr/local/final
COPY . .
RUN ./gradlew clean build

### stage 1, run time
FROM adoptopenjdk/openjdk11
WORKDIR /usr/local/final
COPY --from=build-stage /usr/local/final /usr/local/final